# Generated by Django 5.2.1 on 2025-06-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_to_cross', models.JSONField()),
                ('exists_date', models.JSONField()),
                ('fields_name', models.JSONField()),
                ('prioritys', models.JSONField()),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
