# Generated by Django 5.2.1 on 2025-06-11 19:54

import webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossdata',
            old_name='data_to_cross',
            new_name='data_from_sf',
        ),
        migrations.RenameField(
            model_name='crossdata',
            old_name='exists_date',
            new_name='data_from_page',
        ),
        migrations.RenameField(
            model_name='crossdata',
            old_name='prioritys',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='crossdata',
            name='uuid',
            field=models.CharField(default=webhooks.models.get_unique_id, max_length=255, unique=True),
        ),
    ]
