# Generated by Django 5.2.1 on 2025-06-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_rename_data_to_cross_crossdata_data_from_sf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossdata',
            name='fields',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
