# Generated by Django 5.2.1 on 2025-06-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_crossdata_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossdata',
            name='fields_name',
        ),
        migrations.RemoveField(
            model_name='crossdata',
            name='priority',
        ),
    ]
