# Generated by Django 5.1.1 on 2024-10-08 11:57

import django.db.models.deletion
import locks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_id_ttl', models.IntegerField(unique=True)),
                ('lock_name', models.CharField(blank=True, max_length=300, null=True)),
                ('lock_alias', models.CharField(blank=True, max_length=300, null=True)),
                ('electric_quantity', models.IntegerField(default=0)),
                ('has_gateway', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='PassageMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('is_cyclic', models.BooleanField()),
                ('unlock_in_active', models.BooleanField()),
                ('type_range', models.IntegerField()),
                ('start_range', models.CharField(max_length=50)),
                ('end_range', models.CharField(max_length=50)),
                ('type_start_time', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('type_end_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('error_level', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=1)),
                ('done', models.IntegerField(default=0)),
                ('send_webhook', models.BooleanField(default=0)),
                ('active_now', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('person_phone', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50, null=True)),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('status_record', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sunset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minute', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.IntegerField()),
                ('lock_name', models.CharField(max_length=50)),
                ('card_description', models.CharField(max_length=50)),
                ('status_transmission', models.IntegerField(default=0)),
                ('amount_attempts', models.IntegerField(default=0)),
                ('last_transmission', models.BigIntegerField(null=True)),
                ('permission_id', models.IntegerField()),
                ('date_create', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('user_transmission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15, unique=True)),
                ('link_code', models.CharField(default=locks.models.generate_random_string, max_length=15)),
                ('lock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locks.lock')),
            ],
        ),
        migrations.CreateModel(
            name='LockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField()),
                ('record_type_from_lock', models.IntegerField()),
                ('record_type', models.IntegerField()),
                ('success', models.BooleanField()),
                ('username', models.CharField(max_length=50, null=True)),
                ('keyboard_pwd', models.CharField(max_length=50)),
                ('person_id', models.IntegerField(null=True)),
                ('person_name', models.CharField(max_length=50, null=True)),
                ('type_object_id', models.IntegerField(null=True)),
                ('object_record_description', models.CharField(max_length=50, null=True)),
                ('lock_date', models.BigIntegerField()),
                ('server_date', models.BigIntegerField()),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
            ],
        ),
        migrations.CreateModel(
            name='LocksHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.house')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
            ],
        ),
        migrations.CreateModel(
            name='LockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassageModeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.passagemode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('card_permission_id', models.IntegerField(null=True)),
                ('type_permission', models.IntegerField()),
                ('start_date', models.BigIntegerField(null=True)),
                ('end_date', models.BigIntegerField(null=True)),
                ('cyclic_config', models.JSONField(null=True)),
                ('grant_by', models.CharField(max_length=50, null=True)),
                ('status_record', models.IntegerField(default=0)),
                ('date_add', models.BigIntegerField(null=True)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
                ('type_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_object', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HostingIchilov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_feedback', models.BooleanField(default=0)),
                ('hospital_ward', models.CharField(max_length=50, null=True)),
                ('lodging_start', models.DateField()),
                ('lodging_end', models.DateField()),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locks.person')),
            ],
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.CharField(max_length=50, null=True)),
                ('guest_is_patient', models.BooleanField(default=0)),
                ('lodging_start', models.DateField()),
                ('lodging_end', models.DateField()),
                ('hospital_ward', models.CharField(max_length=50, null=True)),
                ('trigger', models.CharField(max_length=50, null=True)),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('send_feedback', models.BooleanField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locks.house')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostings_as_guest', to='locks.person')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostings_as_patient', to='locks.person')),
            ],
        ),
        migrations.CreateModel(
            name='LockAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.accessgroup')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
            ],
            options={
                'unique_together': {('lock', 'access_group')},
            },
        ),
        migrations.CreateModel(
            name='PassageModeLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_status', models.IntegerField(default=0)),
                ('passage_time', models.IntegerField(default=0)),
                ('unlock_status', models.IntegerField(default=0)),
                ('unlock_time', models.IntegerField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
                ('passage_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.passagemode')),
            ],
            options={
                'unique_together': {('passage_mode', 'lock')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10, unique=True)),
                ('card_name', models.CharField(max_length=50)),
                ('status_record', models.IntegerField(default=0)),
                ('coffee_card', models.IntegerField(default=0)),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='locks.person')),
            ],
            options={
                'unique_together': {('card_name', 'person')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('phone_name', models.CharField(max_length=50)),
                ('date_add', models.BigIntegerField(default=locks.models.default_timestamp)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.person')),
            ],
            options={
                'unique_together': {('phone_name', 'person')},
            },
        ),
    ]
