# Generated by Django 5.1.1 on 2024-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='trigger',
        ),
    ]
