# Generated by Django 5.1.1 on 2024-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_remove_hosting_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='trigger',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
