# Generated by Django 5.1.1 on 2024-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_hosting_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='page_description',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
