# Generated by Django 5.1.1 on 2024-10-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0004_house_page_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_is_patient', models.BooleanField(default=0)),
                ('affinity', models.CharField(max_length=50, null=True)),
                ('hospital_ward', models.CharField(max_length=50, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_hostings_as_guest', to='locks.person')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_hostings_as_patient', to='locks.person')),
            ],
        ),
    ]
