# Generated by Django 5.1.1 on 2024-10-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0005_hostingrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostingRecords',
            new_name='HostingRecord',
        ),
    ]
