# Generated by Django 5.1.1 on 2024-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0006_rename_hostingrecords_hostingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
