# Generated by Django 5.1.1 on 2024-10-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0007_person_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='view_in_last',
            field=models.BooleanField(default=1),
        ),
    ]
