# Generated by Django 5.1.1 on 2024-10-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0008_person_view_in_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='view_in_last',
        ),
    ]
