# Generated by Django 5.1.1 on 2024-10-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0009_remove_person_view_in_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='documents',
            field=models.BooleanField(default=0),
        ),
    ]
