# Generated by Django 4.2.16 on 2024-10-27 09:31

from django.db import migrations, models
import django.db.models.deletion
import locks.models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0010_hosting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10, unique=True)),
                ('date_create', models.BigIntegerField(default=locks.models.default_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='HousesReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('guest_status', models.CharField(max_length=50)),
                ('patiant_name', models.CharField(max_length=50)),
                ('hospital_ward', models.CharField(max_length=50)),
                ('lodging_start', models.DateField()),
                ('lodging_end', models.DateField()),
                ('clean', models.BooleanField()),
                ('clean_check_out', models.BooleanField()),
                ('meal', models.BooleanField()),
                ('fault', models.BooleanField()),
                ('missing_documents', models.BooleanField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.house')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.housesreport')),
            ],
        ),
    ]
