# Generated by Django 4.2.16 on 2024-10-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0011_housesreport_housesreportrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='guest_status',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='hospital_ward',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='lodging_end',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='lodging_start',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='patiant_name',
        ),
    ]
