# Generated by Django 4.2.16 on 2024-10-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0012_remove_housesreportrecord_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesreportrecord',
            name='missing_documents',
        ),
    ]
