# Generated by Django 4.2.16 on 2024-10-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0013_remove_housesreportrecord_missing_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesreport',
            name='report_date',
            field=models.DateField(default='2024-10-10'),
            preserve_default=False,
        ),
    ]
