# Generated by Django 4.2.16 on 2024-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0014_housesreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='not_to_view',
            field=models.BooleanField(default=False),
        ),
    ]
