# Generated by Django 4.2.16 on 2024-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0015_person_not_to_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
