# Generated by Django 4.2.16 on 2024-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0016_hosting_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesreport',
            name='description',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
