# Generated by Django 4.2.16 on 2024-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0017_alter_housesreport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesreportrecord',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housesreportrecord',
            name='clean_check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housesreportrecord',
            name='fault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housesreportrecord',
            name='meal',
            field=models.BooleanField(default=False),
        ),
    ]
