# Generated by Django 4.2.16 on 2024-10-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0018_alter_housesreportrecord_clean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
