# Generated by Django 4.2.16 on 2024-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0019_alter_person_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesreportrecord',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
