# Generated by Django 4.2.16 on 2024-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0020_housesreportrecord_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='trigger',
            field=models.CharField(default='', max_length=50),
        ),
    ]
