# Generated by Django 4.2.16 on 2024-10-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0021_alter_hosting_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
