# Generated by Django 4.2.16 on 2024-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0022_house_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='file',
            field=models.BooleanField(default=0),
        ),
    ]
