# Generated by Django 4.2.16 on 2024-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0023_hosting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
