# Generated by Django 4.2.16 on 2024-10-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0024_alter_hosting_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='file',
        ),
    ]
