# Generated by Django 4.2.16 on 2024-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0025_remove_hosting_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
