# Generated by Django 4.2.16 on 2024-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0026_hosting_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='file',
        ),
        migrations.AddField(
            model_name='hosting',
            name='file_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
