# Generated by Django 4.2.16 on 2024-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0027_remove_hosting_file_hosting_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='page_description',
            new_name='page_description1',
        ),
        migrations.AddField(
            model_name='house',
            name='page_description2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
