# Generated by Django 4.2.16 on 2024-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0029_alter_house_page_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='page_description1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='page_description2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
