# Generated by Django 4.2.16 on 2024-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0030_alter_house_page_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='persons_in_house',
            field=models.IntegerField(default=0),
        ),
    ]
