# Generated by Django 4.2.16 on 2024-11-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0031_hosting_persons_in_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='card_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
