# Generated by Django 4.2.16 on 2024-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0032_transmission_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockrecord',
            name='done_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
