# Generated by Django 4.2.16 on 2024-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0033_lockrecord_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockrecord',
            name='done_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lockrecord',
            name='object_record_description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
