# Generated by Django 4.2.16 on 2025-01-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0035_houseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('clean_check_out', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('fault', models.BooleanField(default=False)),
                ('note', models.CharField(default='', max_length=300)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.hosting')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.housesreport')),
            ],
        ),
    ]
