# Generated by Django 4.2.16 on 2025-02-03 20:32

from django.db import migrations, models
import django.db.models.deletion
import locks.models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0036_hostingreportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True)),
                ('report_date', models.DateField()),
                ('date_create', models.BigIntegerField(default=locks.models.default_timestamp)),
            ],
        ),
        migrations.AlterField(
            model_name='hostingreportrecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.hostingreport'),
        ),
    ]
