# Generated by Django 4.2.16 on 2025-02-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0037_hostingreport_alter_hostingreportrecord_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingreportrecord',
            name='hosting',
        ),
        migrations.RemoveField(
            model_name='hostingreportrecord',
            name='report',
        ),
        migrations.DeleteModel(
            name='HostingReport',
        ),
        migrations.DeleteModel(
            name='HostingReportRecord',
        ),
    ]
