# Generated by Django 4.2.16 on 2025-02-04 20:37

from django.db import migrations, models
import django.db.models.deletion
import locks.models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0038_remove_hostingreportrecord_hosting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesReport_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True)),
                ('report_date', models.DateField()),
                ('date_create', models.BigIntegerField(default=locks.models.default_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='HousesReportRecord_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('clean_check_out', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('fault', models.BooleanField(default=False)),
                ('note', models.CharField(default='', max_length=300)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.house')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.housesreport_dev')),
            ],
        ),
    ]
