# Generated by Django 4.2.16 on 2025-02-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0039_housesreport_dev_housesreportrecord_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesreportrecord_dev',
            name='house',
        ),
        migrations.RemoveField(
            model_name='housesreportrecord_dev',
            name='report',
        ),
        migrations.DeleteModel(
            name='HousesReport_dev',
        ),
        migrations.DeleteModel(
            name='HousesReportRecord_dev',
        ),
    ]
