# Generated by Django 4.2.16 on 2025-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0040_remove_housesreportrecord_dev_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesreportrecord',
            name='bed',
            field=models.BooleanField(default=False),
        ),
    ]
