# Generated by Django 4.2.16 on 2025-02-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0041_housesreportrecord_bed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='file_path',
            new_name='file_path1',
        ),
        migrations.AddField(
            model_name='hosting',
            name='file_path2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
