# Generated by Django 4.2.20 on 2025-05-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0042_rename_file_path_hosting_file_path1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name_eng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_eng',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
