# Generated by Django 4.2.20 on 2025-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0043_person_first_name_eng_person_last_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='hospital_ward_eng',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
