# Generated by Django 4.2.20 on 2025-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0044_hosting_hospital_ward_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='hospital_ward_eng',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
