# Generated by Django 4.2.20 on 2025-05-06 12:04

from django.db import migrations, models
import locks.models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0045_alter_hosting_hospital_ward_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default=locks.models.generate_random_string, max_length=50, unique=True)),
            ],
        ),
    ]
