# Generated by Django 4.2.20 on 2025-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0046_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='page_description1_eng',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='page_description2_eng',
            field=models.CharField(default='', max_length=50),
        ),
    ]
