# Generated by Django 5.2.1 on 2025-06-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0047_house_page_description1_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='page_description1_eng',
        ),
        migrations.RemoveField(
            model_name='house',
            name='page_description2_eng',
        ),
    ]
