# Generated by Django 5.2.3 on 2025-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0048_remove_house_page_description1_eng_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lockrecord',
            index=models.Index(fields=['lock', 'keyboard_pwd'], name='locks_lockr_lock_id_f30172_idx'),
        ),
    ]
