# Generated by Django 5.2.3 on 2025-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0049_lockrecord_locks_lockr_lock_id_f30172_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_number_file',
            field=models.FileField(blank=True, null=True, upload_to='id_number_files/'),
        ),
    ]
